version: 2

updates:
  - package-ecosystem: 'composer'
    directory: '/dev-tools'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'php-cs-fixer/diff'
    labels:
      - 'dependencies'
    reviewers:
      - 'kubawerlos'
    versioning-strategy: 'increase'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'kubawerlos'
