version: 2

updates:
  - package-ecosystem: composer
    directory: /.dev-tools
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
      timezone: Europe/Warsaw
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
      timezone: Europe/Warsaw
